spring:

  jackson:
    dateFormat: yyyy-MM-dd'T'hh:mm:ss

  redis:
    host: 139.159.147.239
    port: 6379

  rabbitmq:
      host: 139.159.147.239
      port: 5672
      username: b2b
      password: kzj365
      publisher-confirms: true
      publisher-returns: true
      listener:
        direct:
          acknowledge-mode: manual
        simple:
          acknowledge-mode: manual
  servlet:
    multipart:
      max-file-size: 21MB
      max-request-size: 20MB
      enabled: true


ribbon:
  ReadTimeout: 4000
  ConnectTimeout: 4000

eureka:
  instance:
    hostname: ${spring.cloud.client.ip-address}
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 9
  client:
    serviceUrl:
      defaultZone: http://139.159.147.239:8085/eureka/

# 配置hystrix
feign:
  hystrix:
    enabled: true

hystrix:
  threadpool:
    default:
      coreSize: 100  #线程池核心线程数
  command:
    #IService#hello(): 设置某一个接口 default: 设置全部接口
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000 #超时时间
      circuitBreaker:
        requestVolumeThreshold: 100  #当在配置时间窗口内达到此数量后，进行短路。默认20个
        sleepWindowInMilliseconds: 5000  #短路多久以后开始尝试是否恢复，默认5s/单位毫秒
        errorThresholdPercentage: 50%  #出错百分比阈值，当达到此阈值后，开始短路。默认50%


mybatis:
    mapper-locations: classpath:mapping/*.xml
    type-aliases-package: com.b2b.module.commodity.model
    configuration:
#         控制台输出mybatis的sql
          log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
    helperDialect: mysql
    reasonable: false
    supportMethodsArguments: true
    params: count=countSql


tx-lcn:
  client:
    manager-address: 139.159.147.239:8070 #可填写多个负载

appContext:
  swagger:
    host:
    
management:
  endpoints:
    web:
      exposure:
        include: refresh
